import type { Metadata } from "next";
import React from "react";
import { Montserrat } from "next/font/google";
import "./globals.css";
import "./theme.css";
import TranslationProvider from "@/providers/TranslationProvider";
import ThemeProvider from "@/providers/ThemeProvider";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Drojas",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className={montserrat.className}
			style={{
				colorScheme: "light dark",
			}}
		>
			<body className="bg-main-bg-color">
				<TranslationProvider>
					<ThemeProvider>{children}</ThemeProvider>
				</TranslationProvider>
			</body>
		</html>
	);
}
