import type { Metadata } from "next";
import React from "react";
import { Montserrat } from "next/font/google";
import "./globals.css";
import TranslationProvider from "@/providers/TranslationProvider";
import ThemeProvider from "@/providers/ThemeProvider";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Drojas",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
  children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={montserrat.className}>
				<TranslationProvider>
					<ThemeProvider>{children}</ThemeProvider>
				</TranslationProvider>
			</body>
		</html>
	);
}
